version: '3.8'

services:
  database:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - 27017:27017
volumes:
  mongodb_data_container: